---
version: "3"
services:
  mariadb:
    image: mariadb:10.4
    environment:
      MARIADB_ROOT_PASSWORD: juve
    volumes: 
    - /mariadb_data:/var/lib/mysql 

  flask-app:
    build: .
    image: ef38/capge-flaskapp
    ports:
    - 5000:5000
    depends_on:
    - mariadb 
    restart: always
