---
version: "3"
services:
  database:
    image: mariadb:10.4
    environment:
      MARIADB_ROOT_HOST: mariadb
      MARIADB_ROOT_USER: delpiero
      MARIADB_ROOT_PASSWORD: juve
      MARIADB_ROOT_DB: exo3
    volumes: 
    - mariadb:/data 

  flask-app:
    build: .
    image: ef38/capge-flaskapp
    ports:
    - 5000:5000
    depends_on:
    - database 
    restart: always
    volumes:
    - "./public:/app/public" 

volumes:
  mariadb: {}
  
