---
apiVersion: v1
kind: Namespace
metadata:
  name: exo3
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
  - ReadWriteOnce 
  resources:
    requests: 
      storage: 2Gi 
     
---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
  namespace: exo3
  labels:
    app: mariadb

spec:
  containers:
  - name: mariadb-container
    image: mariadb:10.4
    ports:
    - containerPort: 3306
    resources: 
      requests:
        memory: "128Mi"
        cpu: "500m" # 1/2 du processeur
      limits:
        memory: "256Mi"
        cpu: "750m"
    env: 
    - name: MARIADB_ROOT_PASSWORD
      value: juve
#   volumeMounts: 
#    - name: mariadb-volume
#      mountPath: /data
  volumes: 
  - name: mariadb-volume
    persistentVolumeClaim:
      claimName: mariadb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc 
  namespace: exo3
spec:
  type: ClusterIP 
  selector: 
    app : mariadb
  ports:
  - port: 3306
    targetPort: 3306     
    protocol: TCP 