---
apiVersion: v1
kind: Namespace
metadata:
  name: exo3
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exo3
  name: flask-deploy
  labels:
    app: flaskapp    

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp-container
        image: ef38/capge-flaskapp:1.0.0
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: exo3
spec:
  type: NodePort 
  selector: 
    app : flaskapp
  ports:
  - port: 80
    targetPort: 5000     
    nodePort: 30468
    protocol: TCP 

    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: exo3
  name: mariadb-pvc
  labels:
    app: mariadb
spec:
  accessModes:
  - ReadWriteOnce 
  resources:
    requests: 
      storage: 2Gi 
     
---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb-pod
  namespace: exo3
  labels:
    app: mariadb

spec:
  containers:
  - name: mariadb-container
    image: mariadb:10.4
    ports:
    - containerPort: 3306
    resources: 
      requests:
        memory: "128Mi"
        cpu: "500m" # 1/2 du processeur
      limits:
        memory: "256Mi"
        cpu: "750m"
    env: 
    - name: MARIADB_ROOT_PASSWORD
      value: juve
    - name: MARIADB_USER
      value: delpiero
    - name: MARIADB_PASSWORD
      value: juve
    volumeMounts: 
     - name: mariadb-volume
       mountPath: /var/lib/mysql
  volumes: 
  - name: mariadb-volume
    persistentVolumeClaim:
      claimName: mariadb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc 
  namespace: exo3
spec:
  type: ClusterIP 
  selector: 
    app : mariadb
  ports:
  - port: 3306
    targetPort: 3306     
    protocol: TCP 
