---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exo3
  name: flask-deploy
  labels:
    app: flaskapp    

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp-container
        image: ef38/capge-flaskapp:1.0.0
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: exo3
spec:
  type: NodePort 
  selector: 
    app : flaskapp
  ports:
  - port: 5000
    targetPort: 5000     
    nodePort: 32000
    protocol: TCP 